version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.12

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install tox

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            tox

  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            docker build --target devenv -t openmaraude/geotaxi-python-devenv:${CIRCLE_TAG} .
            docker tag openmaraude/geotaxi-python-devenv:${CIRCLE_TAG} openmaraude/geotaxi-python-devenv:latest

            docker build -t openmaraude/geotaxi-python:${CIRCLE_TAG} .
            docker tag openmaraude/geotaxi-python:${CIRCLE_TAG} openmaraude/geotaxi-python:latest
      - run:
          name: Publish docker Image to hub.docker.com
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

            docker push openmaraude/geotaxi-python-devenv:${CIRCLE_TAG}
            docker push openmaraude/geotaxi-python-devenv:latest

            docker push openmaraude/geotaxi-python:${CIRCLE_TAG}
            docker push openmaraude/geotaxi-python:latest

workflows:
  version: 2

  test:
    jobs:
      - test

  # Build artifacts, ignore all branches, only run for all tags.
  artifacts:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/

      - build:
          requires:
            - test
          filters:
            tags:
              only: /.*/
