version: 2

jobs:
  test:
    docker:
      - image: circleci/python:3

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install tox

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            tox

workflows:
  version: 2

  test:
    jobs:
      - test
