__author__ = 'Julien Castets'
__contact__ = 'julien.castets@beta.gouv.fr'
__homepage__ = 'https://github.com/openmaraude/geotaxi-python'
__version__ = '0.1.4'
__doc__ = 'UDP server to store realtime taxi positions'
