#After editing this file, run `geotaxi-generate-jsonschema`, it will generate geotaxi/jsonschema.py file
#Never edit geotaxi/jsonschema.py by yourself

import fastjsonschema

API_SCHEMA = {
    'type': 'object',
    'properties': {
        'operator':  {'type': 'string'},
        'lat':       {'type':  ['number', 'string']},
        'device':    {'type': 'string'},
        'lon':       {'type': ['number', 'string']},
        'timestamp': {'type': ['number', 'string']},
        'status':    {'type': 'string'},
        'version':   {'type': 'string'},
        'taxi':      {'type': 'string'},
        'hash':      {'type': 'string'},
    },
    'required': [
        'operator', 'lat', 'device', 'lon', 'timestamp', 'status', 'version', 'taxi', 'hash',
    ]
}

WARNING_MESSAGE = """# File generated by the command `geotaxi-generate-jsonschema`, do not edit by yourself
# To modify it, edit API_SCHEMA variable in geotaxi/jsonschema_definition.pt and the run `geotaxi-generate-jsonschema

"""

def main():
    with open('geotaxi/jsonschema.py', 'w') as f:
        f.write(WARNING_MESSAGE)
        f.write(fastjsonschema.compile_to_code(API_SCHEMA))
